# Build settings

port: 4000
markdown:  kramdown
permalink: 
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Darren Bridger"
description: "Powered by Jekyll and GitHub Pages"
author:      "djb"
